### ISSUE TITLE
Any way to provide DeathAudio from a different folder?

### ISSUE THREAD

**Issue by JohnMetroid** [BoredBean/CustomDeathAudio#1]
Hey there, this mod is really neat!  Is there a way to provide the DeathAudio file from a different folder so that it can be customized via a different mod pack on thunderstore?

Thanks

**Comment by BoredBean** [comment]
Hi, glad to hear you liked it. I will try to make the path configurable.

**Comment by BoredBean** [comment]
Done.

**Comment by JohnMetroid** [comment]
Had some time tonight to test it and hook it into a different pack.  Looks good.

Thanks so much!
