### ISSUE TITLE
[Bug] custom death sound will play at the beginning of the next day

### ISSUE THREAD

**Issue by JohnMetroid** [BoredBean/CustomDeathAudio#2]
Hey there, we've been using the mod for a few days now, so I thought we should report the one little quirk we found.  In both single player and 2 player multiplayer, we hear the custom death sound play pretty much as the next level is starting if someone died the prior day.  It is heard when loaded back into the ship in space, right around when the daily recap messages pop up.

I don't have a better way to relay the bug at the moment (logs don't have anything of importance, I don't think?).  But if I manage to get a good video or some relevant information I'll be sure to pass it along.

**Comment by BoredBean** [comment]
Thanks for your information. I will do some tests on this.

**Comment by BoredBean** [comment]
I've tested a few times single player but have not encountered this issue. 
Please make sure you are at least at v1.1.0.

**Comment by BoredBean** [comment]
I found it in multiplayer games. Looking for the reason

**Comment by BoredBean** [comment]
I believe it's fixed, but I'm not 100% sure of it.

Please re-open the issue if it happens again in the latest version.
