### ISSUE TITLE
[bug?] bootup issue with 2.0.1

### ISSUE THREAD

**Issue by JohnMetroid** [BoredBean/CustomDeathAudio#3]
hey, i recently updated from 1.3.0 to 2.0.1, and on bootup I now get:

![image](https://github.com/BoredBean/CustomDeathAudio/assets/139426529/af309523-bf7d-48a9-9081-40442f8ea46c)

I have LCSoundTool 1.5.1 already

**Comment by BoredBean** [comment]
Thanks for your feedback!

I've been confused by the source code of LCSoundTool.
It defined the PLUGIN_GUID twice and I picked the wrong one.
😂

**Comment by BoredBean** [comment]
This should be fixed at v2.1.0
